name: "eca-check"
on:
  pull_request:

permissions:
  statuses: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for eclipsefdn/eca status check to complete
        uses: autotelic/action-wait-for-status-check@v1
        id: wait-for-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "eclipsefdn/eca"

      - name: Fail if not successful
        uses: actions/github-script@v3
        if: ${{ steps.wait-for-status.outputs.state != 'success' }}
        with:
          script: |
            core.setFailed('${{ steps.wait-for-status.outputs.description }}')
