name: "eca-check"
on:
  pull_request:

permissions:
  checks: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for eclipsefdn/eca status check to complete
        uses: autotelic/action-wait-for-status-check@v1
        id: wait-for-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "eclipsefdn/eca"
