name: "eca validation test"
on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: OtterdogTest/eca-action@main
